import "server-only";

export const PRO_MONTHLY_PROCESSED_EMAIL_LIMIT = 500;
export const DAILY_PROCESSED_EMAIL_LIMIT = 30;
export const USER_RUNS_PER_MINUTE_LIMIT = 5;
export const USER_RUNS_PER_TEN_MINUTES_LIMIT = 20;

export const USER_CONCURRENT_EXECUTION_LIMIT = 1;
export const SYSTEM_CONCURRENT_EXECUTION_LIMIT = 5;
export const EXECUTION_LEASE_TTL_MS = 75_000;

export const SYSTEM_EXECUTIONS_PER_TEN_MINUTES_LIMIT = 50;
export const SYSTEM_EXECUTIONS_PER_HOUR_LIMIT = 100;
export const SYSTEM_EXECUTIONS_PER_UTC_DAY_LIMIT = 500;
export const SYSTEM_EXECUTIONS_PER_UTC_MONTH_LIMIT = 1_000;

export const CRON_RULES_PER_USER_INVOCATION_LIMIT = 100;
export const CRON_RULES_PER_SYSTEM_INVOCATION_LIMIT = 500;

export const RAW_EMAIL_BODY_LIMIT_BYTES = 100 * 1_024;
export const ATTACHMENT_COUNT_LIMIT = 5;
export const SINGLE_ATTACHMENT_LIMIT_BYTES = 10 * 1_024 * 1_024;
export const TOTAL_ATTACHMENT_LIMIT_BYTES = 25 * 1_024 * 1_024;
export const GENERATED_PDF_LIMIT_BYTES = 10 * 1_024 * 1_024;
export const TOTAL_DRIVE_WRITE_PER_EMAIL_LIMIT_BYTES = 35 * 1_024 * 1_024;
export const USER_MONTHLY_DRIVE_WRITE_LIMIT_BYTES = 1 * 1_024 * 1_024 * 1_024;
export const SYSTEM_MONTHLY_DRIVE_WRITE_LIMIT_BYTES = 5 * 1_024 * 1_024 * 1_024;

export const EXECUTION_ABSOLUTE_DEADLINE_MS = 60_000;
export const GMAIL_CUMULATIVE_TIMEOUT_MS = 15_000;
export const OPENAI_TIMEOUT_MS = 8_000;
export const DRIVE_CUMULATIVE_TIMEOUT_MS = 30_000;
export const DB_FINALIZATION_RESERVE_MS = 3_000;

export const RETRY_SAFE_MAX_RETRIES = 1;
export const OPENAI_MAX_RETRIES = 0;
export const UNKNOWN_EXTERNAL_WRITE_MAX_RETRIES = 0;

export const OPENAI_MAX_INPUT_TOKENS = 4_000;
export const OPENAI_MAX_OUTPUT_TOKENS = 20;
export const OPENAI_MAX_CALLS_PER_EMAIL = 1;
