import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  let isGoogleConnected = false;
  let hasActiveRule = false;

  if (user) {
    // Google接続判定
    const { data: gc } = await supabase
      .from("google_connections")
      .select("id")
      .eq("user_id", user.id)
      .maybeSingle();

    isGoogleConnected = !!gc;

    // 🔴 ここから追加
    // 直近エラー取得
    let lastErrorRun: {
      rule_id: string | null;
      finished_at: string | null;
      message: string | null;
    } | null = null;

    const { data: myRules } = await supabase
      .from("rules")
      .select("id")
      .eq("user_id", user.id);

    const ruleIds = (myRules ?? []).map((x) => x.id);

    if (ruleIds.length > 0) {
      const { data: errRun } = await supabase
        .from("runs")
        .select("rule_id, finished_at, message")
        .in("rule_id", ruleIds)
        .eq("status", "error")
        .order("finished_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      lastErrorRun = errRun ?? null;
    }

    // 有効ルール判定（まず is_active を採用）
    const { data: rules } = await supabase
      .from("rules")
      .select("id")
      .eq("user_id", user.id)
      .eq("is_active", true)
      .limit(1);

    hasActiveRule = !!rules && rules.length > 0;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {user && !isGoogleConnected && (
          <div className="ap-banner">
            <span className="ap-banner__text">
              Googleアカウントが未接続です。自動実行を利用するには接続が必要です。
            </span>

            <a href="/api/google/connect" className="ap-banner__action">
              <button className="ap-banner__btn">Googleに接続</button>
            </a>
          </div>
        )}
        {user && isGoogleConnected && !hasActiveRule && (
          <div className="ap-banner ap-banner--info">
            <span className="ap-banner__text">
              有効なルールがありません。まずはルールを作成してください。
            </span>

            <a href="/rules/new" className="ap-banner__action">
              <button className="ap-banner__btn ap-banner__btn--info">
                ルールを作成
              </button>
            </a>
          </div>
        )}
        {user && isGoogleConnected && lastErrorRun && (
          <div className="ap-banner ap-banner--danger">
            <span className="ap-banner__text">
              直近の実行でエラーが発生しています。設定を確認してください。
            </span>

            <a
              href={
                lastErrorRun.rule_id
                  ? `/rules/${lastErrorRun.rule_id}`
                  : "/rules"
              }
              className="ap-banner__action"
            >
              <button className="ap-banner__btn ap-banner__btn--danger">
                確認する
              </button>
            </a>
          </div>
        )}

        {children}
        <style>{`
  .ap-banner{
  background:#FEF3C7;
  border-bottom:1px solid #F59E0B;
  padding:12px 20px;
  display:flex;
  justify-content:space-between;
  align-items:center;
  gap:12px;
  font-size:14px;
  color:#1F2937; /* ← 追加してもOK */
}
  .ap-banner__text{
  line-height:1.4;
  color:#1F2937; /* ← 追加（濃いグレー） */
  font-weight:500;
}
  .ap-banner__action{
    flex:0 0 auto;
  }
  .ap-banner__btn{
    background:#4F46E5;
    color:#fff;
    padding:8px 14px;
    border-radius:999px;
    border:none;
    cursor:pointer;
    font-weight:600;
    white-space:nowrap;
  }
    .ap-banner--info{
  background:#E0F2FE;
  border-bottom:1px solid #38BDF8;
}
.ap-banner__btn--info{
  background:#2563EB;
}
  .ap-banner--danger{
  background:#FEE2E2;
  border-bottom:1px solid #FCA5A5;
}
.ap-banner__btn--danger{
  background:#DC2626;
}

  /* ✅ スマホだけ：テキストの下にボタン、ボタンは右寄せ（3枚目の配置） */
  @media (max-width: 640px){
    .ap-banner{
      flex-direction:column;
      align-items:stretch;
    }
    .ap-banner__action{
      display:flex;
      justify-content:flex-end;
    }
  }
`}</style>
      </body>
    </html>
  );
}
